// This file is auto-generated by scripts/generate-template-hash.ts
// Do not edit manually. Run "pnpm generate:hash" to regenerate.
export const TEMPLATE_HASH = "532e0";

export function getTemplateHash(): string {
	return TEMPLATE_HASH;
}
