import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT_DIR = resolve(import.meta.dirname, "..");

/**
 * Generate a template hash for ETag versioning.
 * The hash changes when template or theme metadata changes.
 */
export function generateTemplateHash(): string {
	const inputPaths = [
		resolve(ROOT_DIR, "shared/templates/view.template.tsx"),
		resolve(ROOT_DIR, "shared/themes/theme-registry.ts"),
	];
	const hash = createHash("md5");

	for (const inputPath of inputPaths) {
		hash.update(readFileSync(inputPath, "utf-8"));
	}

	return hash.digest("hex").slice(0, 5);
}

function main() {
	const templateHash = generateTemplateHash();

	const outputPath = resolve(
		ROOT_DIR,
		"shared/templates/template-hash.generated.ts",
	);
	const content = `// This file is auto-generated by scripts/generate-template-hash.ts
// Do not edit manually. Run "pnpm generate:hash" to regenerate.
export const TEMPLATE_HASH = "${templateHash}";

export function getTemplateHash(): string {
	return TEMPLATE_HASH;
}
`;

	writeFileSync(outputPath, content);
	console.log("✓ Generated template hash:", templateHash);
}

const isDirectExecution = (() => {
	const entryFromArgv = process.argv[1];
	if (!entryFromArgv) return false;
	return fileURLToPath(import.meta.url) === entryFromArgv;
})();

if (isDirectExecution) {
	main();
}
