import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");

/**
 * Generate a hash from template and theme files for ETag versioning.
 * This hash changes when any of the following files are modified:
 * - shared/templates/view.template.ts
 * - public/themes/*.css
 */
function generateTemplateHash(): string {
	const hash = createHash("md5");

	// Add view.template.ts content
	const templatePath = resolve(root, "shared/templates/view.template.ts");
	const templateContent = readFileSync(templatePath, "utf-8");
	hash.update(templateContent);

	// Add all theme CSS files
	const themesDir = resolve(root, "public/themes");
	const themeFiles = readdirSync(themesDir)
		.filter((file) => file.endsWith(".css"))
		.sort(); // Sort for consistent ordering

	for (const file of themeFiles) {
		const filePath = resolve(themesDir, file);
		const content = readFileSync(filePath, "utf-8");
		hash.update(content);
	}

	return hash.digest("hex").slice(0, 5);
}

function main() {
	const templateHash = generateTemplateHash();

	const outputPath = resolve(
		root,
		"shared/templates/template-hash.generated.ts",
	);
	const content = `// This file is auto-generated by scripts/generate-template-hash.ts
// Do not edit manually. Run "pnpm generate:hash" to regenerate.
export const TEMPLATE_HASH = "${templateHash}";
`;

	writeFileSync(outputPath, content);
	console.log(`✓ Generated template hash: ${templateHash}`);
}

main();
